// Tool registry — 10 canonical MCP tools mirroring the loadgen
// defaultMCPTools list in aforo-nextgen-loadgen/internal/generator/fields.go
// so scenarios generated by loadgen map 1:1 to tools this server handles.
//
// Every handler is deterministic and side-effect-free: returns a synthetic
// text/json payload plus optional simulated latency. The server is a
// STAND-IN for a real MCP server — good enough to prove a JSON-RPC tools/call
// reaches it, is metered by the layer under test (gateway plugin, SDK, or
// proxy sidecar), and produces a valid response the client can parse.

import type { McpTool, McpToolsCallResult } from './types.js';

interface ToolHandler {
  spec: McpTool;
  /** Optional per-tool simulated latency in ms (0-N). */
  latencyMs?: number;
  /** Synchronous handler — returns the tools/call result payload. */
  handle: (args: Record<string, unknown>) => McpToolsCallResult;
}

// Duration heuristics — the "heavy" tools take longer, mirroring the
// mcpServerTemplate in loadgen (vector_search / summarize / extract_entities
// get +200-1000ms).
const HEAVY_MS = 300;
const LIGHT_MS = 5;

const registry: Record<string, ToolHandler> = {
  search_web: {
    spec: {
      name: 'search_web',
      description: 'Search the web for a query. Returns synthetic results.',
      inputSchema: {
        type: 'object',
        properties: { query: { type: 'string' } },
        required: ['query'],
      },
    },
    latencyMs: HEAVY_MS,
    handle: (args) => textResult(
      `search_web results for "${String(args.query ?? '')}" — 3 hits (synthetic)`,
    ),
  },
  read_file: {
    spec: {
      name: 'read_file',
      description: 'Read a file at the given path. Returns synthetic contents.',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' } },
        required: ['path'],
      },
    },
    latencyMs: LIGHT_MS,
    handle: (args) => textResult(
      `--- ${String(args.path ?? '')} (synthetic) ---\nline 1\nline 2\n`,
    ),
  },
  write_file: {
    spec: {
      name: 'write_file',
      description: 'Write a file (no-op — returns acknowledgement only).',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, contents: { type: 'string' } },
        required: ['path', 'contents'],
      },
    },
    latencyMs: LIGHT_MS,
    handle: (args) => textResult(
      `wrote ${String((args.contents as string ?? '').length)} bytes to ${String(args.path ?? '')} (synthetic)`,
    ),
  },
  execute_query: {
    spec: {
      name: 'execute_query',
      description: 'Execute a database query. Returns synthetic row data.',
      inputSchema: {
        type: 'object',
        properties: { sql: { type: 'string' } },
        required: ['sql'],
      },
    },
    latencyMs: HEAVY_MS,
    handle: (args) => jsonResult({
      query: String(args.sql ?? ''),
      rows: [{ id: 1, name: 'synthetic-a' }, { id: 2, name: 'synthetic-b' }],
      rowCount: 2,
    }),
  },
  vector_search: {
    spec: {
      name: 'vector_search',
      description: 'Vector similarity search. Returns synthetic top-K results.',
      inputSchema: {
        type: 'object',
        properties: { query: { type: 'string' }, top_k: { type: 'number' } },
        required: ['query'],
      },
    },
    latencyMs: HEAVY_MS,
    handle: (args) => jsonResult({
      query: String(args.query ?? ''),
      matches: [
        { id: 'doc-1', score: 0.92 },
        { id: 'doc-2', score: 0.87 },
        { id: 'doc-3', score: 0.81 },
      ],
    }),
  },
  summarize: {
    spec: {
      name: 'summarize',
      description: 'Summarize a text passage. Returns a synthetic summary.',
      inputSchema: {
        type: 'object',
        properties: { text: { type: 'string' } },
        required: ['text'],
      },
    },
    latencyMs: HEAVY_MS,
    handle: (args) => textResult(
      `Summary: ${String(args.text ?? '').slice(0, 60)}... (synthetic)`,
    ),
  },
  translate: {
    spec: {
      name: 'translate',
      description: 'Translate text between languages. Returns synthetic output.',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string' },
          from: { type: 'string' },
          to: { type: 'string' },
        },
        required: ['text', 'to'],
      },
    },
    latencyMs: HEAVY_MS,
    handle: (args) => textResult(
      `[${String(args.to ?? 'en')}] ${String(args.text ?? '')} (synthetic)`,
    ),
  },
  classify: {
    spec: {
      name: 'classify',
      description: 'Classify text into a category. Returns synthetic labels.',
      inputSchema: {
        type: 'object',
        properties: { text: { type: 'string' } },
        required: ['text'],
      },
    },
    latencyMs: LIGHT_MS,
    handle: () => jsonResult({
      labels: [
        { name: 'category-a', confidence: 0.71 },
        { name: 'category-b', confidence: 0.24 },
      ],
    }),
  },
  send_email: {
    spec: {
      name: 'send_email',
      description: 'Send an email (no-op — returns synthetic message id).',
      inputSchema: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          subject: { type: 'string' },
          body: { type: 'string' },
        },
        required: ['to'],
      },
    },
    latencyMs: LIGHT_MS,
    handle: (args) => jsonResult({
      messageId: `msg_${Date.now()}`,
      to: String(args.to ?? ''),
      status: 'queued',
    }),
  },
  create_record: {
    spec: {
      name: 'create_record',
      description: 'Create a record in a synthetic store. Returns record id.',
      inputSchema: {
        type: 'object',
        properties: {
          collection: { type: 'string' },
          data: { type: 'object' },
        },
        required: ['collection'],
      },
    },
    latencyMs: LIGHT_MS,
    handle: (args) => jsonResult({
      id: `rec_${Date.now()}`,
      collection: String(args.collection ?? 'default'),
      created: true,
    }),
  },
};

export function listTools(): McpTool[] {
  return Object.values(registry).map((h) => h.spec);
}

export function hasTool(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(registry, name);
}

export async function callTool(
  name: string,
  args: Record<string, unknown>,
  opts: { simulateLatency?: boolean } = {},
): Promise<McpToolsCallResult> {
  const handler = registry[name];
  if (!handler) {
    return {
      isError: true,
      content: [{ type: 'text', text: `unknown tool: ${name}` }],
    };
  }
  if (opts.simulateLatency && handler.latencyMs) {
    await new Promise((r) => setTimeout(r, handler.latencyMs));
  }
  return handler.handle(args);
}

function textResult(text: string): McpToolsCallResult {
  return { content: [{ type: 'text', text }] };
}

function jsonResult(data: unknown): McpToolsCallResult {
  return { content: [{ type: 'json', data }] };
}
